baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "GGan' Blog"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
  # DoIt 主题版本
  version = "0.2.X"

[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false


[languages.zh-cn.params]
      # 网站描述
      description = "GGAN"
      # 网站关键词
      keywords = ["Theme", "Hugo"]
      # 应用图标配置
      [languages.zh-cn.params.app]
        # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
        title = "DoIt"
        # 是否隐藏网站图标资源链接
        noFavicon = false
        # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
        svgFavicon = ""
        # Safari 图标颜色
        iconColor = "#5bbad5"
        # Windows v8-10 磁贴颜色
        tileColor = "#da532c"

# 主页信息设置
      [languages.zh-cn.params.home]
        # RSS 文章数目
        rss = 10
        # 主页个人信息
        [languages.zh-cn.params.home.profile]
          enable = true
          # Gravatar 邮箱，用于优先在主页显示的头像
          gravatarEmail = ""
          # 主页显示头像的 URL
          avatarURL = "/images/logo.png"
          # 主页显示的网站标题 (支持 HTML 格式)
          title = ""
          # 主页显示的网站副标题
          subtitle = "欢迎来到GGan的博客！"
          # 是否为副标题显示打字机动画
          typeit = true
          # 是否显示社交账号
          social = true
          # 免责声明 (支持 HTML 格式)
          disclaimer = ""
        # 主页文章列表
        [languages.zh-cn.params.home.posts]
          enable = true
          # 主页每页显示文章数量
          paginate = 7
      # 主页的社交信息设置
      [languages.zh-cn.params.social]
        Angellist = ""
        Bandcamp = ""
        Behance = ""
        Bilibili = "394985962"
        Bitbucket = ""
        BuyMeACoffee = ""
        Codepen = ""
        Deviantart = ""
        Devto = ""
        Douban = ""
        Dribbble = ""
        Email = "xxxx@xxxx.com"
        Facebook = ""
        Fivehundredpx = ""
        Flickr = ""
        Foursquare = ""
        FreeCodeCamp = ""
        Gitea = ""
        GitHub = "WJGGan"
        Gitlab = ""
        Goodreads = ""
        Googlescholar = ""
        Hackernews = ""
        Instagram = ""
        Jsfiddle = ""
        Keybase = ""
        Kickstarter = ""
        Ko-Fi = ""
        Lastfm = ""
        Liberapay = ""
        Linkedin = ""
        Linktree = ""
        Mastodon = ""
        Matrix = ""
        Medium = ""
        Mix = ""
        Odnoklassniki = ""
        ORCID = ""
        Patreon = ""
        Paypal = ""
        Pinterest = ""
        QQ = ""
        QQGroup = ""
        Quora = ""
        Reddit = ""
        Researchgate = ""
        RSS = true
        Skype = ""
        Slidershare = ""
        Snapchat = ""
        Soundcloud = ""
        Spotify = ""
        Stackoverflow = ""
        Steam = ""
        Strava = ""
        Telegram = ""
        Thingiverse = ""
        Tumblr = ""
        Twitch = ""
        Twitter = ""
        Vine = ""
        VK = ""
        Weibo = "u/5794299185"
        Whatsapp = ""
        Wordpress = ""
        Xing = ""
        XMPP = ""
        Youtubechannel = ""
        Youtubecustom = ""
        Youtubelegacy = ""
        Zhihu = "wang-jia-gan-96"
        # 赞助设置
      [languages.zh-cn.params.sponsor]
        enable = false
        bio = "如果你觉得这篇文章对你有所帮助，欢迎赞赏~"
        link = "https://github.com/sponsors/HEIGE-PCloud"
        # custom = "<a href=\"https://www.buymeacoffee.com/PCloud\" target=\"_blank\"><img src=\"https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png\" alt=\"Buy Me A Coffee\" style=\"height: 40px !important;width: 145 !important;\" ></a>"

# Footer config
  # 页面底部信息配置
  [params.footer]
    enable = true
    # Custom content (HTML format is supported)
    # 自定义内容 (支持 HTML 格式)
    custom = ''
    # whether to show Hugo and theme info
    # 是否显示 Hugo 和主题信息
    hugo = true
    # Hosted on (HTML format is supported)
    # 托管服务信息 (支持 HTML 格式)
    # <a title="Github Pages" href="https://docs.github.com/en/pages/" target="_blank" rel="noopener noreffer">GitHub Pages</a>
    hostedOn = '' 
    # whether to show copyright info
    # 是否显示版权信息
    copyright = true
    # whether to show the author
    # 是否显示作者
    author = true
    # site creation time
    # 网站创立年份
    since = 2023
    # ICP info only in China (HTML format is supported)
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # license info (HTML format is supported)
    # 许可协议信息 (支持 HTML 格式)
    license= '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

# Section (all posts) page config
  # Section (所有文章) 页面配置
  [params.section]
    # special amount of posts in each section page
    # section 页面每页显示文章数量
    paginate = 20
    # date format (month and day)
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # amount of RSS pages
    # RSS 文章数目
    rss = 10
    # recently updated posts settings
    # 最近更新文章设置
    [params.section.recentlyUpdated]
      enable = true
      rss = true
      days = 30
      maxCount = 10